/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UniversitiesRouteImport } from './routes/universities'
import { Route as SupportRouteImport } from './routes/support'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeesRouteImport } from './routes/fees'
import { Route as EnrollmentRouteImport } from './routes/enrollment'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CounsellorsRouteImport } from './routes/counsellors'
import { Route as CommissionsRouteImport } from './routes/commissions'
import { Route as CallsRouteImport } from './routes/calls'
import { Route as AdministrationRouteImport } from './routes/administration'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UniversitiesIndexRouteImport } from './routes/universities.index'
import { Route as StudentsIndexRouteImport } from './routes/students.index'
import { Route as EnrollmentIndexRouteImport } from './routes/enrollment.index'
import { Route as CounsellorsIndexRouteImport } from './routes/counsellors.index'
import { Route as AdministrationIndexRouteImport } from './routes/administration.index'
import { Route as UniversitiesUniversitiesRouteImport } from './routes/universities.universities'
import { Route as UniversitiesIntakesRouteImport } from './routes/universities.intakes'
import { Route as UniversitiesFeeStructureRouteImport } from './routes/universities.fee-structure'
import { Route as UniversitiesCoursesRouteImport } from './routes/universities.courses'
import { Route as StudentsStudentsRouteImport } from './routes/students.students'
import { Route as StudentsApplicationsRouteImport } from './routes/students.applications'
import { Route as EnrollmentUniversityWiseRouteImport } from './routes/enrollment.university-wise'
import { Route as EnrollmentStudentsRouteImport } from './routes/enrollment.students'
import { Route as EnrollmentReRegistrationRouteImport } from './routes/enrollment.re-registration'
import { Route as EnrollmentIntakeWiseRouteImport } from './routes/enrollment.intake-wise'
import { Route as CounsellorsTeamsRouteImport } from './routes/counsellors.teams'
import { Route as CounsellorsTargetsRouteImport } from './routes/counsellors.targets'
import { Route as CounsellorsGroupsRouteImport } from './routes/counsellors.groups'
import { Route as CounsellorsCounsellorsRouteImport } from './routes/counsellors.counsellors'
import { Route as AdministrationUsersRouteImport } from './routes/administration.users'
import { Route as AdministrationRolesRouteImport } from './routes/administration.roles'
import { Route as AdministrationAuditLogsRouteImport } from './routes/administration.audit-logs'
import { Route as StudentsStudentsIndexRouteImport } from './routes/students.students.index'
import { Route as StudentsApplicationsIndexRouteImport } from './routes/students.applications.index'
import { Route as UniversitiesUniversitiesCodeRouteImport } from './routes/universities.universities_.$code'
import { Route as StudentsStudentsIdRouteImport } from './routes/students.students.$id'
import { Route as StudentsApplicationsNewRouteImport } from './routes/students.applications.new'
import { Route as CounsellorsTeamProfileTeamIdRouteImport } from './routes/counsellors.team-profile.$teamId'
import { Route as CounsellorsProfileEmpIdRouteImport } from './routes/counsellors.profile.$empId'

const UniversitiesRoute = UniversitiesRouteImport.update({
  id: '/universities',
  path: '/universities',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeesRoute = FeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => rootRouteImport,
} as any)
const EnrollmentRoute = EnrollmentRouteImport.update({
  id: '/enrollment',
  path: '/enrollment',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CounsellorsRoute = CounsellorsRouteImport.update({
  id: '/counsellors',
  path: '/counsellors',
  getParentRoute: () => rootRouteImport,
} as any)
const CommissionsRoute = CommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsRoute = CallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationRoute = AdministrationRouteImport.update({
  id: '/administration',
  path: '/administration',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversitiesIndexRoute = UniversitiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UniversitiesRoute,
} as any)
const StudentsIndexRoute = StudentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentsRoute,
} as any)
const EnrollmentIndexRoute = EnrollmentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnrollmentRoute,
} as any)
const CounsellorsIndexRoute = CounsellorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CounsellorsRoute,
} as any)
const AdministrationIndexRoute = AdministrationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdministrationRoute,
} as any)
const UniversitiesUniversitiesRoute =
  UniversitiesUniversitiesRouteImport.update({
    id: '/universities',
    path: '/universities',
    getParentRoute: () => UniversitiesRoute,
  } as any)
const UniversitiesIntakesRoute = UniversitiesIntakesRouteImport.update({
  id: '/intakes',
  path: '/intakes',
  getParentRoute: () => UniversitiesRoute,
} as any)
const UniversitiesFeeStructureRoute =
  UniversitiesFeeStructureRouteImport.update({
    id: '/fee-structure',
    path: '/fee-structure',
    getParentRoute: () => UniversitiesRoute,
  } as any)
const UniversitiesCoursesRoute = UniversitiesCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => UniversitiesRoute,
} as any)
const StudentsStudentsRoute = StudentsStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => StudentsRoute,
} as any)
const StudentsApplicationsRoute = StudentsApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => StudentsRoute,
} as any)
const EnrollmentUniversityWiseRoute =
  EnrollmentUniversityWiseRouteImport.update({
    id: '/university-wise',
    path: '/university-wise',
    getParentRoute: () => EnrollmentRoute,
  } as any)
const EnrollmentStudentsRoute = EnrollmentStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => EnrollmentRoute,
} as any)
const EnrollmentReRegistrationRoute =
  EnrollmentReRegistrationRouteImport.update({
    id: '/re-registration',
    path: '/re-registration',
    getParentRoute: () => EnrollmentRoute,
  } as any)
const EnrollmentIntakeWiseRoute = EnrollmentIntakeWiseRouteImport.update({
  id: '/intake-wise',
  path: '/intake-wise',
  getParentRoute: () => EnrollmentRoute,
} as any)
const CounsellorsTeamsRoute = CounsellorsTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => CounsellorsRoute,
} as any)
const CounsellorsTargetsRoute = CounsellorsTargetsRouteImport.update({
  id: '/targets',
  path: '/targets',
  getParentRoute: () => CounsellorsRoute,
} as any)
const CounsellorsGroupsRoute = CounsellorsGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => CounsellorsRoute,
} as any)
const CounsellorsCounsellorsRoute = CounsellorsCounsellorsRouteImport.update({
  id: '/counsellors',
  path: '/counsellors',
  getParentRoute: () => CounsellorsRoute,
} as any)
const AdministrationUsersRoute = AdministrationUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdministrationRoute,
} as any)
const AdministrationRolesRoute = AdministrationRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdministrationRoute,
} as any)
const AdministrationAuditLogsRoute = AdministrationAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdministrationRoute,
} as any)
const StudentsStudentsIndexRoute = StudentsStudentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentsStudentsRoute,
} as any)
const StudentsApplicationsIndexRoute =
  StudentsApplicationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StudentsApplicationsRoute,
  } as any)
const UniversitiesUniversitiesCodeRoute =
  UniversitiesUniversitiesCodeRouteImport.update({
    id: '/universities_/$code',
    path: '/universities/$code',
    getParentRoute: () => UniversitiesRoute,
  } as any)
const StudentsStudentsIdRoute = StudentsStudentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StudentsStudentsRoute,
} as any)
const StudentsApplicationsNewRoute = StudentsApplicationsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => StudentsApplicationsRoute,
} as any)
const CounsellorsTeamProfileTeamIdRoute =
  CounsellorsTeamProfileTeamIdRouteImport.update({
    id: '/team-profile/$teamId',
    path: '/team-profile/$teamId',
    getParentRoute: () => CounsellorsRoute,
  } as any)
const CounsellorsProfileEmpIdRoute = CounsellorsProfileEmpIdRouteImport.update({
  id: '/profile/$empId',
  path: '/profile/$empId',
  getParentRoute: () => CounsellorsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/administration': typeof AdministrationRouteWithChildren
  '/calls': typeof CallsRoute
  '/commissions': typeof CommissionsRoute
  '/counsellors': typeof CounsellorsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/enrollment': typeof EnrollmentRouteWithChildren
  '/fees': typeof FeesRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/students': typeof StudentsRouteWithChildren
  '/support': typeof SupportRoute
  '/universities': typeof UniversitiesRouteWithChildren
  '/administration/audit-logs': typeof AdministrationAuditLogsRoute
  '/administration/roles': typeof AdministrationRolesRoute
  '/administration/users': typeof AdministrationUsersRoute
  '/counsellors/counsellors': typeof CounsellorsCounsellorsRoute
  '/counsellors/groups': typeof CounsellorsGroupsRoute
  '/counsellors/targets': typeof CounsellorsTargetsRoute
  '/counsellors/teams': typeof CounsellorsTeamsRoute
  '/enrollment/intake-wise': typeof EnrollmentIntakeWiseRoute
  '/enrollment/re-registration': typeof EnrollmentReRegistrationRoute
  '/enrollment/students': typeof EnrollmentStudentsRoute
  '/enrollment/university-wise': typeof EnrollmentUniversityWiseRoute
  '/students/applications': typeof StudentsApplicationsRouteWithChildren
  '/students/students': typeof StudentsStudentsRouteWithChildren
  '/universities/courses': typeof UniversitiesCoursesRoute
  '/universities/fee-structure': typeof UniversitiesFeeStructureRoute
  '/universities/intakes': typeof UniversitiesIntakesRoute
  '/universities/universities': typeof UniversitiesUniversitiesRoute
  '/administration/': typeof AdministrationIndexRoute
  '/counsellors/': typeof CounsellorsIndexRoute
  '/enrollment/': typeof EnrollmentIndexRoute
  '/students/': typeof StudentsIndexRoute
  '/universities/': typeof UniversitiesIndexRoute
  '/counsellors/profile/$empId': typeof CounsellorsProfileEmpIdRoute
  '/counsellors/team-profile/$teamId': typeof CounsellorsTeamProfileTeamIdRoute
  '/students/applications/new': typeof StudentsApplicationsNewRoute
  '/students/students/$id': typeof StudentsStudentsIdRoute
  '/universities/universities/$code': typeof UniversitiesUniversitiesCodeRoute
  '/students/applications/': typeof StudentsApplicationsIndexRoute
  '/students/students/': typeof StudentsStudentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calls': typeof CallsRoute
  '/commissions': typeof CommissionsRoute
  '/dashboard': typeof DashboardRoute
  '/fees': typeof FeesRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/support': typeof SupportRoute
  '/administration/audit-logs': typeof AdministrationAuditLogsRoute
  '/administration/roles': typeof AdministrationRolesRoute
  '/administration/users': typeof AdministrationUsersRoute
  '/counsellors/counsellors': typeof CounsellorsCounsellorsRoute
  '/counsellors/groups': typeof CounsellorsGroupsRoute
  '/counsellors/targets': typeof CounsellorsTargetsRoute
  '/counsellors/teams': typeof CounsellorsTeamsRoute
  '/enrollment/intake-wise': typeof EnrollmentIntakeWiseRoute
  '/enrollment/re-registration': typeof EnrollmentReRegistrationRoute
  '/enrollment/students': typeof EnrollmentStudentsRoute
  '/enrollment/university-wise': typeof EnrollmentUniversityWiseRoute
  '/universities/courses': typeof UniversitiesCoursesRoute
  '/universities/fee-structure': typeof UniversitiesFeeStructureRoute
  '/universities/intakes': typeof UniversitiesIntakesRoute
  '/universities/universities': typeof UniversitiesUniversitiesRoute
  '/administration': typeof AdministrationIndexRoute
  '/counsellors': typeof CounsellorsIndexRoute
  '/enrollment': typeof EnrollmentIndexRoute
  '/students': typeof StudentsIndexRoute
  '/universities': typeof UniversitiesIndexRoute
  '/counsellors/profile/$empId': typeof CounsellorsProfileEmpIdRoute
  '/counsellors/team-profile/$teamId': typeof CounsellorsTeamProfileTeamIdRoute
  '/students/applications/new': typeof StudentsApplicationsNewRoute
  '/students/students/$id': typeof StudentsStudentsIdRoute
  '/universities/universities/$code': typeof UniversitiesUniversitiesCodeRoute
  '/students/applications': typeof StudentsApplicationsIndexRoute
  '/students/students': typeof StudentsStudentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/administration': typeof AdministrationRouteWithChildren
  '/calls': typeof CallsRoute
  '/commissions': typeof CommissionsRoute
  '/counsellors': typeof CounsellorsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/enrollment': typeof EnrollmentRouteWithChildren
  '/fees': typeof FeesRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/students': typeof StudentsRouteWithChildren
  '/support': typeof SupportRoute
  '/universities': typeof UniversitiesRouteWithChildren
  '/administration/audit-logs': typeof AdministrationAuditLogsRoute
  '/administration/roles': typeof AdministrationRolesRoute
  '/administration/users': typeof AdministrationUsersRoute
  '/counsellors/counsellors': typeof CounsellorsCounsellorsRoute
  '/counsellors/groups': typeof CounsellorsGroupsRoute
  '/counsellors/targets': typeof CounsellorsTargetsRoute
  '/counsellors/teams': typeof CounsellorsTeamsRoute
  '/enrollment/intake-wise': typeof EnrollmentIntakeWiseRoute
  '/enrollment/re-registration': typeof EnrollmentReRegistrationRoute
  '/enrollment/students': typeof EnrollmentStudentsRoute
  '/enrollment/university-wise': typeof EnrollmentUniversityWiseRoute
  '/students/applications': typeof StudentsApplicationsRouteWithChildren
  '/students/students': typeof StudentsStudentsRouteWithChildren
  '/universities/courses': typeof UniversitiesCoursesRoute
  '/universities/fee-structure': typeof UniversitiesFeeStructureRoute
  '/universities/intakes': typeof UniversitiesIntakesRoute
  '/universities/universities': typeof UniversitiesUniversitiesRoute
  '/administration/': typeof AdministrationIndexRoute
  '/counsellors/': typeof CounsellorsIndexRoute
  '/enrollment/': typeof EnrollmentIndexRoute
  '/students/': typeof StudentsIndexRoute
  '/universities/': typeof UniversitiesIndexRoute
  '/counsellors/profile/$empId': typeof CounsellorsProfileEmpIdRoute
  '/counsellors/team-profile/$teamId': typeof CounsellorsTeamProfileTeamIdRoute
  '/students/applications/new': typeof StudentsApplicationsNewRoute
  '/students/students/$id': typeof StudentsStudentsIdRoute
  '/universities/universities_/$code': typeof UniversitiesUniversitiesCodeRoute
  '/students/applications/': typeof StudentsApplicationsIndexRoute
  '/students/students/': typeof StudentsStudentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/administration'
    | '/calls'
    | '/commissions'
    | '/counsellors'
    | '/dashboard'
    | '/enrollment'
    | '/fees'
    | '/login'
    | '/reports'
    | '/students'
    | '/support'
    | '/universities'
    | '/administration/audit-logs'
    | '/administration/roles'
    | '/administration/users'
    | '/counsellors/counsellors'
    | '/counsellors/groups'
    | '/counsellors/targets'
    | '/counsellors/teams'
    | '/enrollment/intake-wise'
    | '/enrollment/re-registration'
    | '/enrollment/students'
    | '/enrollment/university-wise'
    | '/students/applications'
    | '/students/students'
    | '/universities/courses'
    | '/universities/fee-structure'
    | '/universities/intakes'
    | '/universities/universities'
    | '/administration/'
    | '/counsellors/'
    | '/enrollment/'
    | '/students/'
    | '/universities/'
    | '/counsellors/profile/$empId'
    | '/counsellors/team-profile/$teamId'
    | '/students/applications/new'
    | '/students/students/$id'
    | '/universities/universities/$code'
    | '/students/applications/'
    | '/students/students/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calls'
    | '/commissions'
    | '/dashboard'
    | '/fees'
    | '/login'
    | '/reports'
    | '/support'
    | '/administration/audit-logs'
    | '/administration/roles'
    | '/administration/users'
    | '/counsellors/counsellors'
    | '/counsellors/groups'
    | '/counsellors/targets'
    | '/counsellors/teams'
    | '/enrollment/intake-wise'
    | '/enrollment/re-registration'
    | '/enrollment/students'
    | '/enrollment/university-wise'
    | '/universities/courses'
    | '/universities/fee-structure'
    | '/universities/intakes'
    | '/universities/universities'
    | '/administration'
    | '/counsellors'
    | '/enrollment'
    | '/students'
    | '/universities'
    | '/counsellors/profile/$empId'
    | '/counsellors/team-profile/$teamId'
    | '/students/applications/new'
    | '/students/students/$id'
    | '/universities/universities/$code'
    | '/students/applications'
    | '/students/students'
  id:
    | '__root__'
    | '/'
    | '/administration'
    | '/calls'
    | '/commissions'
    | '/counsellors'
    | '/dashboard'
    | '/enrollment'
    | '/fees'
    | '/login'
    | '/reports'
    | '/students'
    | '/support'
    | '/universities'
    | '/administration/audit-logs'
    | '/administration/roles'
    | '/administration/users'
    | '/counsellors/counsellors'
    | '/counsellors/groups'
    | '/counsellors/targets'
    | '/counsellors/teams'
    | '/enrollment/intake-wise'
    | '/enrollment/re-registration'
    | '/enrollment/students'
    | '/enrollment/university-wise'
    | '/students/applications'
    | '/students/students'
    | '/universities/courses'
    | '/universities/fee-structure'
    | '/universities/intakes'
    | '/universities/universities'
    | '/administration/'
    | '/counsellors/'
    | '/enrollment/'
    | '/students/'
    | '/universities/'
    | '/counsellors/profile/$empId'
    | '/counsellors/team-profile/$teamId'
    | '/students/applications/new'
    | '/students/students/$id'
    | '/universities/universities_/$code'
    | '/students/applications/'
    | '/students/students/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdministrationRoute: typeof AdministrationRouteWithChildren
  CallsRoute: typeof CallsRoute
  CommissionsRoute: typeof CommissionsRoute
  CounsellorsRoute: typeof CounsellorsRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  EnrollmentRoute: typeof EnrollmentRouteWithChildren
  FeesRoute: typeof FeesRoute
  LoginRoute: typeof LoginRoute
  ReportsRoute: typeof ReportsRoute
  StudentsRoute: typeof StudentsRouteWithChildren
  SupportRoute: typeof SupportRoute
  UniversitiesRoute: typeof UniversitiesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/universities': {
      id: '/universities'
      path: '/universities'
      fullPath: '/universities'
      preLoaderRoute: typeof UniversitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fees': {
      id: '/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof FeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enrollment': {
      id: '/enrollment'
      path: '/enrollment'
      fullPath: '/enrollment'
      preLoaderRoute: typeof EnrollmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counsellors': {
      id: '/counsellors'
      path: '/counsellors'
      fullPath: '/counsellors'
      preLoaderRoute: typeof CounsellorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commissions': {
      id: '/commissions'
      path: '/commissions'
      fullPath: '/commissions'
      preLoaderRoute: typeof CommissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls': {
      id: '/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof CallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration': {
      id: '/administration'
      path: '/administration'
      fullPath: '/administration'
      preLoaderRoute: typeof AdministrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/universities/': {
      id: '/universities/'
      path: '/'
      fullPath: '/universities/'
      preLoaderRoute: typeof UniversitiesIndexRouteImport
      parentRoute: typeof UniversitiesRoute
    }
    '/students/': {
      id: '/students/'
      path: '/'
      fullPath: '/students/'
      preLoaderRoute: typeof StudentsIndexRouteImport
      parentRoute: typeof StudentsRoute
    }
    '/enrollment/': {
      id: '/enrollment/'
      path: '/'
      fullPath: '/enrollment/'
      preLoaderRoute: typeof EnrollmentIndexRouteImport
      parentRoute: typeof EnrollmentRoute
    }
    '/counsellors/': {
      id: '/counsellors/'
      path: '/'
      fullPath: '/counsellors/'
      preLoaderRoute: typeof CounsellorsIndexRouteImport
      parentRoute: typeof CounsellorsRoute
    }
    '/administration/': {
      id: '/administration/'
      path: '/'
      fullPath: '/administration/'
      preLoaderRoute: typeof AdministrationIndexRouteImport
      parentRoute: typeof AdministrationRoute
    }
    '/universities/universities': {
      id: '/universities/universities'
      path: '/universities'
      fullPath: '/universities/universities'
      preLoaderRoute: typeof UniversitiesUniversitiesRouteImport
      parentRoute: typeof UniversitiesRoute
    }
    '/universities/intakes': {
      id: '/universities/intakes'
      path: '/intakes'
      fullPath: '/universities/intakes'
      preLoaderRoute: typeof UniversitiesIntakesRouteImport
      parentRoute: typeof UniversitiesRoute
    }
    '/universities/fee-structure': {
      id: '/universities/fee-structure'
      path: '/fee-structure'
      fullPath: '/universities/fee-structure'
      preLoaderRoute: typeof UniversitiesFeeStructureRouteImport
      parentRoute: typeof UniversitiesRoute
    }
    '/universities/courses': {
      id: '/universities/courses'
      path: '/courses'
      fullPath: '/universities/courses'
      preLoaderRoute: typeof UniversitiesCoursesRouteImport
      parentRoute: typeof UniversitiesRoute
    }
    '/students/students': {
      id: '/students/students'
      path: '/students'
      fullPath: '/students/students'
      preLoaderRoute: typeof StudentsStudentsRouteImport
      parentRoute: typeof StudentsRoute
    }
    '/students/applications': {
      id: '/students/applications'
      path: '/applications'
      fullPath: '/students/applications'
      preLoaderRoute: typeof StudentsApplicationsRouteImport
      parentRoute: typeof StudentsRoute
    }
    '/enrollment/university-wise': {
      id: '/enrollment/university-wise'
      path: '/university-wise'
      fullPath: '/enrollment/university-wise'
      preLoaderRoute: typeof EnrollmentUniversityWiseRouteImport
      parentRoute: typeof EnrollmentRoute
    }
    '/enrollment/students': {
      id: '/enrollment/students'
      path: '/students'
      fullPath: '/enrollment/students'
      preLoaderRoute: typeof EnrollmentStudentsRouteImport
      parentRoute: typeof EnrollmentRoute
    }
    '/enrollment/re-registration': {
      id: '/enrollment/re-registration'
      path: '/re-registration'
      fullPath: '/enrollment/re-registration'
      preLoaderRoute: typeof EnrollmentReRegistrationRouteImport
      parentRoute: typeof EnrollmentRoute
    }
    '/enrollment/intake-wise': {
      id: '/enrollment/intake-wise'
      path: '/intake-wise'
      fullPath: '/enrollment/intake-wise'
      preLoaderRoute: typeof EnrollmentIntakeWiseRouteImport
      parentRoute: typeof EnrollmentRoute
    }
    '/counsellors/teams': {
      id: '/counsellors/teams'
      path: '/teams'
      fullPath: '/counsellors/teams'
      preLoaderRoute: typeof CounsellorsTeamsRouteImport
      parentRoute: typeof CounsellorsRoute
    }
    '/counsellors/targets': {
      id: '/counsellors/targets'
      path: '/targets'
      fullPath: '/counsellors/targets'
      preLoaderRoute: typeof CounsellorsTargetsRouteImport
      parentRoute: typeof CounsellorsRoute
    }
    '/counsellors/groups': {
      id: '/counsellors/groups'
      path: '/groups'
      fullPath: '/counsellors/groups'
      preLoaderRoute: typeof CounsellorsGroupsRouteImport
      parentRoute: typeof CounsellorsRoute
    }
    '/counsellors/counsellors': {
      id: '/counsellors/counsellors'
      path: '/counsellors'
      fullPath: '/counsellors/counsellors'
      preLoaderRoute: typeof CounsellorsCounsellorsRouteImport
      parentRoute: typeof CounsellorsRoute
    }
    '/administration/users': {
      id: '/administration/users'
      path: '/users'
      fullPath: '/administration/users'
      preLoaderRoute: typeof AdministrationUsersRouteImport
      parentRoute: typeof AdministrationRoute
    }
    '/administration/roles': {
      id: '/administration/roles'
      path: '/roles'
      fullPath: '/administration/roles'
      preLoaderRoute: typeof AdministrationRolesRouteImport
      parentRoute: typeof AdministrationRoute
    }
    '/administration/audit-logs': {
      id: '/administration/audit-logs'
      path: '/audit-logs'
      fullPath: '/administration/audit-logs'
      preLoaderRoute: typeof AdministrationAuditLogsRouteImport
      parentRoute: typeof AdministrationRoute
    }
    '/students/students/': {
      id: '/students/students/'
      path: '/'
      fullPath: '/students/students/'
      preLoaderRoute: typeof StudentsStudentsIndexRouteImport
      parentRoute: typeof StudentsStudentsRoute
    }
    '/students/applications/': {
      id: '/students/applications/'
      path: '/'
      fullPath: '/students/applications/'
      preLoaderRoute: typeof StudentsApplicationsIndexRouteImport
      parentRoute: typeof StudentsApplicationsRoute
    }
    '/universities/universities_/$code': {
      id: '/universities/universities_/$code'
      path: '/universities/$code'
      fullPath: '/universities/universities/$code'
      preLoaderRoute: typeof UniversitiesUniversitiesCodeRouteImport
      parentRoute: typeof UniversitiesRoute
    }
    '/students/students/$id': {
      id: '/students/students/$id'
      path: '/$id'
      fullPath: '/students/students/$id'
      preLoaderRoute: typeof StudentsStudentsIdRouteImport
      parentRoute: typeof StudentsStudentsRoute
    }
    '/students/applications/new': {
      id: '/students/applications/new'
      path: '/new'
      fullPath: '/students/applications/new'
      preLoaderRoute: typeof StudentsApplicationsNewRouteImport
      parentRoute: typeof StudentsApplicationsRoute
    }
    '/counsellors/team-profile/$teamId': {
      id: '/counsellors/team-profile/$teamId'
      path: '/team-profile/$teamId'
      fullPath: '/counsellors/team-profile/$teamId'
      preLoaderRoute: typeof CounsellorsTeamProfileTeamIdRouteImport
      parentRoute: typeof CounsellorsRoute
    }
    '/counsellors/profile/$empId': {
      id: '/counsellors/profile/$empId'
      path: '/profile/$empId'
      fullPath: '/counsellors/profile/$empId'
      preLoaderRoute: typeof CounsellorsProfileEmpIdRouteImport
      parentRoute: typeof CounsellorsRoute
    }
  }
}

interface AdministrationRouteChildren {
  AdministrationAuditLogsRoute: typeof AdministrationAuditLogsRoute
  AdministrationRolesRoute: typeof AdministrationRolesRoute
  AdministrationUsersRoute: typeof AdministrationUsersRoute
  AdministrationIndexRoute: typeof AdministrationIndexRoute
}

const AdministrationRouteChildren: AdministrationRouteChildren = {
  AdministrationAuditLogsRoute: AdministrationAuditLogsRoute,
  AdministrationRolesRoute: AdministrationRolesRoute,
  AdministrationUsersRoute: AdministrationUsersRoute,
  AdministrationIndexRoute: AdministrationIndexRoute,
}

const AdministrationRouteWithChildren = AdministrationRoute._addFileChildren(
  AdministrationRouteChildren,
)

interface CounsellorsRouteChildren {
  CounsellorsCounsellorsRoute: typeof CounsellorsCounsellorsRoute
  CounsellorsGroupsRoute: typeof CounsellorsGroupsRoute
  CounsellorsTargetsRoute: typeof CounsellorsTargetsRoute
  CounsellorsTeamsRoute: typeof CounsellorsTeamsRoute
  CounsellorsIndexRoute: typeof CounsellorsIndexRoute
  CounsellorsProfileEmpIdRoute: typeof CounsellorsProfileEmpIdRoute
  CounsellorsTeamProfileTeamIdRoute: typeof CounsellorsTeamProfileTeamIdRoute
}

const CounsellorsRouteChildren: CounsellorsRouteChildren = {
  CounsellorsCounsellorsRoute: CounsellorsCounsellorsRoute,
  CounsellorsGroupsRoute: CounsellorsGroupsRoute,
  CounsellorsTargetsRoute: CounsellorsTargetsRoute,
  CounsellorsTeamsRoute: CounsellorsTeamsRoute,
  CounsellorsIndexRoute: CounsellorsIndexRoute,
  CounsellorsProfileEmpIdRoute: CounsellorsProfileEmpIdRoute,
  CounsellorsTeamProfileTeamIdRoute: CounsellorsTeamProfileTeamIdRoute,
}

const CounsellorsRouteWithChildren = CounsellorsRoute._addFileChildren(
  CounsellorsRouteChildren,
)

interface EnrollmentRouteChildren {
  EnrollmentIntakeWiseRoute: typeof EnrollmentIntakeWiseRoute
  EnrollmentReRegistrationRoute: typeof EnrollmentReRegistrationRoute
  EnrollmentStudentsRoute: typeof EnrollmentStudentsRoute
  EnrollmentUniversityWiseRoute: typeof EnrollmentUniversityWiseRoute
  EnrollmentIndexRoute: typeof EnrollmentIndexRoute
}

const EnrollmentRouteChildren: EnrollmentRouteChildren = {
  EnrollmentIntakeWiseRoute: EnrollmentIntakeWiseRoute,
  EnrollmentReRegistrationRoute: EnrollmentReRegistrationRoute,
  EnrollmentStudentsRoute: EnrollmentStudentsRoute,
  EnrollmentUniversityWiseRoute: EnrollmentUniversityWiseRoute,
  EnrollmentIndexRoute: EnrollmentIndexRoute,
}

const EnrollmentRouteWithChildren = EnrollmentRoute._addFileChildren(
  EnrollmentRouteChildren,
)

interface StudentsApplicationsRouteChildren {
  StudentsApplicationsNewRoute: typeof StudentsApplicationsNewRoute
  StudentsApplicationsIndexRoute: typeof StudentsApplicationsIndexRoute
}

const StudentsApplicationsRouteChildren: StudentsApplicationsRouteChildren = {
  StudentsApplicationsNewRoute: StudentsApplicationsNewRoute,
  StudentsApplicationsIndexRoute: StudentsApplicationsIndexRoute,
}

const StudentsApplicationsRouteWithChildren =
  StudentsApplicationsRoute._addFileChildren(StudentsApplicationsRouteChildren)

interface StudentsStudentsRouteChildren {
  StudentsStudentsIdRoute: typeof StudentsStudentsIdRoute
  StudentsStudentsIndexRoute: typeof StudentsStudentsIndexRoute
}

const StudentsStudentsRouteChildren: StudentsStudentsRouteChildren = {
  StudentsStudentsIdRoute: StudentsStudentsIdRoute,
  StudentsStudentsIndexRoute: StudentsStudentsIndexRoute,
}

const StudentsStudentsRouteWithChildren =
  StudentsStudentsRoute._addFileChildren(StudentsStudentsRouteChildren)

interface StudentsRouteChildren {
  StudentsApplicationsRoute: typeof StudentsApplicationsRouteWithChildren
  StudentsStudentsRoute: typeof StudentsStudentsRouteWithChildren
  StudentsIndexRoute: typeof StudentsIndexRoute
}

const StudentsRouteChildren: StudentsRouteChildren = {
  StudentsApplicationsRoute: StudentsApplicationsRouteWithChildren,
  StudentsStudentsRoute: StudentsStudentsRouteWithChildren,
  StudentsIndexRoute: StudentsIndexRoute,
}

const StudentsRouteWithChildren = StudentsRoute._addFileChildren(
  StudentsRouteChildren,
)

interface UniversitiesRouteChildren {
  UniversitiesCoursesRoute: typeof UniversitiesCoursesRoute
  UniversitiesFeeStructureRoute: typeof UniversitiesFeeStructureRoute
  UniversitiesIntakesRoute: typeof UniversitiesIntakesRoute
  UniversitiesUniversitiesRoute: typeof UniversitiesUniversitiesRoute
  UniversitiesIndexRoute: typeof UniversitiesIndexRoute
  UniversitiesUniversitiesCodeRoute: typeof UniversitiesUniversitiesCodeRoute
}

const UniversitiesRouteChildren: UniversitiesRouteChildren = {
  UniversitiesCoursesRoute: UniversitiesCoursesRoute,
  UniversitiesFeeStructureRoute: UniversitiesFeeStructureRoute,
  UniversitiesIntakesRoute: UniversitiesIntakesRoute,
  UniversitiesUniversitiesRoute: UniversitiesUniversitiesRoute,
  UniversitiesIndexRoute: UniversitiesIndexRoute,
  UniversitiesUniversitiesCodeRoute: UniversitiesUniversitiesCodeRoute,
}

const UniversitiesRouteWithChildren = UniversitiesRoute._addFileChildren(
  UniversitiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdministrationRoute: AdministrationRouteWithChildren,
  CallsRoute: CallsRoute,
  CommissionsRoute: CommissionsRoute,
  CounsellorsRoute: CounsellorsRouteWithChildren,
  DashboardRoute: DashboardRoute,
  EnrollmentRoute: EnrollmentRouteWithChildren,
  FeesRoute: FeesRoute,
  LoginRoute: LoginRoute,
  ReportsRoute: ReportsRoute,
  StudentsRoute: StudentsRouteWithChildren,
  SupportRoute: SupportRoute,
  UniversitiesRoute: UniversitiesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
