/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UniversitiesRouteImport } from './routes/universities'
import { Route as SupportRouteImport } from './routes/support'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeesRouteImport } from './routes/fees'
import { Route as EnrollmentRouteImport } from './routes/enrollment'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CommissionsRouteImport } from './routes/commissions'
import { Route as AdministrationRouteImport } from './routes/administration'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UniversitiesIndexRouteImport } from './routes/universities.index'
import { Route as StudentsIndexRouteImport } from './routes/students.index'
import { Route as UniversitiesUniversitiesRouteImport } from './routes/universities.universities'
import { Route as UniversitiesIntakesRouteImport } from './routes/universities.intakes'
import { Route as UniversitiesFeeStructureRouteImport } from './routes/universities.fee-structure'
import { Route as UniversitiesCoursesRouteImport } from './routes/universities.courses'
import { Route as StudentsStudentsRouteImport } from './routes/students.students'
import { Route as StudentsApplicationsRouteImport } from './routes/students.applications'
import { Route as StudentsStudentsIndexRouteImport } from './routes/students.students.index'
import { Route as StudentsApplicationsIndexRouteImport } from './routes/students.applications.index'
import { Route as UniversitiesUniversitiesCodeRouteImport } from './routes/universities.universities_.$code'
import { Route as StudentsStudentsIdRouteImport } from './routes/students.students.$id'
import { Route as StudentsApplicationsNewRouteImport } from './routes/students.applications.new'

const UniversitiesRoute = UniversitiesRouteImport.update({
  id: '/universities',
  path: '/universities',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeesRoute = FeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => rootRouteImport,
} as any)
const EnrollmentRoute = EnrollmentRouteImport.update({
  id: '/enrollment',
  path: '/enrollment',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CommissionsRoute = CommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationRoute = AdministrationRouteImport.update({
  id: '/administration',
  path: '/administration',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversitiesIndexRoute = UniversitiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UniversitiesRoute,
} as any)
const StudentsIndexRoute = StudentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentsRoute,
} as any)
const UniversitiesUniversitiesRoute =
  UniversitiesUniversitiesRouteImport.update({
    id: '/universities',
    path: '/universities',
    getParentRoute: () => UniversitiesRoute,
  } as any)
const UniversitiesIntakesRoute = UniversitiesIntakesRouteImport.update({
  id: '/intakes',
  path: '/intakes',
  getParentRoute: () => UniversitiesRoute,
} as any)
const UniversitiesFeeStructureRoute =
  UniversitiesFeeStructureRouteImport.update({
    id: '/fee-structure',
    path: '/fee-structure',
    getParentRoute: () => UniversitiesRoute,
  } as any)
const UniversitiesCoursesRoute = UniversitiesCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => UniversitiesRoute,
} as any)
const StudentsStudentsRoute = StudentsStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => StudentsRoute,
} as any)
const StudentsApplicationsRoute = StudentsApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => StudentsRoute,
} as any)
const StudentsStudentsIndexRoute = StudentsStudentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentsStudentsRoute,
} as any)
const StudentsApplicationsIndexRoute =
  StudentsApplicationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StudentsApplicationsRoute,
  } as any)
const UniversitiesUniversitiesCodeRoute =
  UniversitiesUniversitiesCodeRouteImport.update({
    id: '/universities_/$code',
    path: '/universities/$code',
    getParentRoute: () => UniversitiesRoute,
  } as any)
const StudentsStudentsIdRoute = StudentsStudentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StudentsStudentsRoute,
} as any)
const StudentsApplicationsNewRoute = StudentsApplicationsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => StudentsApplicationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/administration': typeof AdministrationRoute
  '/commissions': typeof CommissionsRoute
  '/dashboard': typeof DashboardRoute
  '/enrollment': typeof EnrollmentRoute
  '/fees': typeof FeesRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/students': typeof StudentsRouteWithChildren
  '/support': typeof SupportRoute
  '/universities': typeof UniversitiesRouteWithChildren
  '/students/applications': typeof StudentsApplicationsRouteWithChildren
  '/students/students': typeof StudentsStudentsRouteWithChildren
  '/universities/courses': typeof UniversitiesCoursesRoute
  '/universities/fee-structure': typeof UniversitiesFeeStructureRoute
  '/universities/intakes': typeof UniversitiesIntakesRoute
  '/universities/universities': typeof UniversitiesUniversitiesRoute
  '/students/': typeof StudentsIndexRoute
  '/universities/': typeof UniversitiesIndexRoute
  '/students/applications/new': typeof StudentsApplicationsNewRoute
  '/students/students/$id': typeof StudentsStudentsIdRoute
  '/universities/universities/$code': typeof UniversitiesUniversitiesCodeRoute
  '/students/applications/': typeof StudentsApplicationsIndexRoute
  '/students/students/': typeof StudentsStudentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/administration': typeof AdministrationRoute
  '/commissions': typeof CommissionsRoute
  '/dashboard': typeof DashboardRoute
  '/enrollment': typeof EnrollmentRoute
  '/fees': typeof FeesRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/support': typeof SupportRoute
  '/universities/courses': typeof UniversitiesCoursesRoute
  '/universities/fee-structure': typeof UniversitiesFeeStructureRoute
  '/universities/intakes': typeof UniversitiesIntakesRoute
  '/universities/universities': typeof UniversitiesUniversitiesRoute
  '/students': typeof StudentsIndexRoute
  '/universities': typeof UniversitiesIndexRoute
  '/students/applications/new': typeof StudentsApplicationsNewRoute
  '/students/students/$id': typeof StudentsStudentsIdRoute
  '/universities/universities/$code': typeof UniversitiesUniversitiesCodeRoute
  '/students/applications': typeof StudentsApplicationsIndexRoute
  '/students/students': typeof StudentsStudentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/administration': typeof AdministrationRoute
  '/commissions': typeof CommissionsRoute
  '/dashboard': typeof DashboardRoute
  '/enrollment': typeof EnrollmentRoute
  '/fees': typeof FeesRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/students': typeof StudentsRouteWithChildren
  '/support': typeof SupportRoute
  '/universities': typeof UniversitiesRouteWithChildren
  '/students/applications': typeof StudentsApplicationsRouteWithChildren
  '/students/students': typeof StudentsStudentsRouteWithChildren
  '/universities/courses': typeof UniversitiesCoursesRoute
  '/universities/fee-structure': typeof UniversitiesFeeStructureRoute
  '/universities/intakes': typeof UniversitiesIntakesRoute
  '/universities/universities': typeof UniversitiesUniversitiesRoute
  '/students/': typeof StudentsIndexRoute
  '/universities/': typeof UniversitiesIndexRoute
  '/students/applications/new': typeof StudentsApplicationsNewRoute
  '/students/students/$id': typeof StudentsStudentsIdRoute
  '/universities/universities_/$code': typeof UniversitiesUniversitiesCodeRoute
  '/students/applications/': typeof StudentsApplicationsIndexRoute
  '/students/students/': typeof StudentsStudentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/administration'
    | '/commissions'
    | '/dashboard'
    | '/enrollment'
    | '/fees'
    | '/login'
    | '/reports'
    | '/students'
    | '/support'
    | '/universities'
    | '/students/applications'
    | '/students/students'
    | '/universities/courses'
    | '/universities/fee-structure'
    | '/universities/intakes'
    | '/universities/universities'
    | '/students/'
    | '/universities/'
    | '/students/applications/new'
    | '/students/students/$id'
    | '/universities/universities/$code'
    | '/students/applications/'
    | '/students/students/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/administration'
    | '/commissions'
    | '/dashboard'
    | '/enrollment'
    | '/fees'
    | '/login'
    | '/reports'
    | '/support'
    | '/universities/courses'
    | '/universities/fee-structure'
    | '/universities/intakes'
    | '/universities/universities'
    | '/students'
    | '/universities'
    | '/students/applications/new'
    | '/students/students/$id'
    | '/universities/universities/$code'
    | '/students/applications'
    | '/students/students'
  id:
    | '__root__'
    | '/'
    | '/administration'
    | '/commissions'
    | '/dashboard'
    | '/enrollment'
    | '/fees'
    | '/login'
    | '/reports'
    | '/students'
    | '/support'
    | '/universities'
    | '/students/applications'
    | '/students/students'
    | '/universities/courses'
    | '/universities/fee-structure'
    | '/universities/intakes'
    | '/universities/universities'
    | '/students/'
    | '/universities/'
    | '/students/applications/new'
    | '/students/students/$id'
    | '/universities/universities_/$code'
    | '/students/applications/'
    | '/students/students/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdministrationRoute: typeof AdministrationRoute
  CommissionsRoute: typeof CommissionsRoute
  DashboardRoute: typeof DashboardRoute
  EnrollmentRoute: typeof EnrollmentRoute
  FeesRoute: typeof FeesRoute
  LoginRoute: typeof LoginRoute
  ReportsRoute: typeof ReportsRoute
  StudentsRoute: typeof StudentsRouteWithChildren
  SupportRoute: typeof SupportRoute
  UniversitiesRoute: typeof UniversitiesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/universities': {
      id: '/universities'
      path: '/universities'
      fullPath: '/universities'
      preLoaderRoute: typeof UniversitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fees': {
      id: '/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof FeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enrollment': {
      id: '/enrollment'
      path: '/enrollment'
      fullPath: '/enrollment'
      preLoaderRoute: typeof EnrollmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commissions': {
      id: '/commissions'
      path: '/commissions'
      fullPath: '/commissions'
      preLoaderRoute: typeof CommissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration': {
      id: '/administration'
      path: '/administration'
      fullPath: '/administration'
      preLoaderRoute: typeof AdministrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/universities/': {
      id: '/universities/'
      path: '/'
      fullPath: '/universities/'
      preLoaderRoute: typeof UniversitiesIndexRouteImport
      parentRoute: typeof UniversitiesRoute
    }
    '/students/': {
      id: '/students/'
      path: '/'
      fullPath: '/students/'
      preLoaderRoute: typeof StudentsIndexRouteImport
      parentRoute: typeof StudentsRoute
    }
    '/universities/universities': {
      id: '/universities/universities'
      path: '/universities'
      fullPath: '/universities/universities'
      preLoaderRoute: typeof UniversitiesUniversitiesRouteImport
      parentRoute: typeof UniversitiesRoute
    }
    '/universities/intakes': {
      id: '/universities/intakes'
      path: '/intakes'
      fullPath: '/universities/intakes'
      preLoaderRoute: typeof UniversitiesIntakesRouteImport
      parentRoute: typeof UniversitiesRoute
    }
    '/universities/fee-structure': {
      id: '/universities/fee-structure'
      path: '/fee-structure'
      fullPath: '/universities/fee-structure'
      preLoaderRoute: typeof UniversitiesFeeStructureRouteImport
      parentRoute: typeof UniversitiesRoute
    }
    '/universities/courses': {
      id: '/universities/courses'
      path: '/courses'
      fullPath: '/universities/courses'
      preLoaderRoute: typeof UniversitiesCoursesRouteImport
      parentRoute: typeof UniversitiesRoute
    }
    '/students/students': {
      id: '/students/students'
      path: '/students'
      fullPath: '/students/students'
      preLoaderRoute: typeof StudentsStudentsRouteImport
      parentRoute: typeof StudentsRoute
    }
    '/students/applications': {
      id: '/students/applications'
      path: '/applications'
      fullPath: '/students/applications'
      preLoaderRoute: typeof StudentsApplicationsRouteImport
      parentRoute: typeof StudentsRoute
    }
    '/students/students/': {
      id: '/students/students/'
      path: '/'
      fullPath: '/students/students/'
      preLoaderRoute: typeof StudentsStudentsIndexRouteImport
      parentRoute: typeof StudentsStudentsRoute
    }
    '/students/applications/': {
      id: '/students/applications/'
      path: '/'
      fullPath: '/students/applications/'
      preLoaderRoute: typeof StudentsApplicationsIndexRouteImport
      parentRoute: typeof StudentsApplicationsRoute
    }
    '/universities/universities_/$code': {
      id: '/universities/universities_/$code'
      path: '/universities/$code'
      fullPath: '/universities/universities/$code'
      preLoaderRoute: typeof UniversitiesUniversitiesCodeRouteImport
      parentRoute: typeof UniversitiesRoute
    }
    '/students/students/$id': {
      id: '/students/students/$id'
      path: '/$id'
      fullPath: '/students/students/$id'
      preLoaderRoute: typeof StudentsStudentsIdRouteImport
      parentRoute: typeof StudentsStudentsRoute
    }
    '/students/applications/new': {
      id: '/students/applications/new'
      path: '/new'
      fullPath: '/students/applications/new'
      preLoaderRoute: typeof StudentsApplicationsNewRouteImport
      parentRoute: typeof StudentsApplicationsRoute
    }
  }
}

interface StudentsApplicationsRouteChildren {
  StudentsApplicationsNewRoute: typeof StudentsApplicationsNewRoute
  StudentsApplicationsIndexRoute: typeof StudentsApplicationsIndexRoute
}

const StudentsApplicationsRouteChildren: StudentsApplicationsRouteChildren = {
  StudentsApplicationsNewRoute: StudentsApplicationsNewRoute,
  StudentsApplicationsIndexRoute: StudentsApplicationsIndexRoute,
}

const StudentsApplicationsRouteWithChildren =
  StudentsApplicationsRoute._addFileChildren(StudentsApplicationsRouteChildren)

interface StudentsStudentsRouteChildren {
  StudentsStudentsIdRoute: typeof StudentsStudentsIdRoute
  StudentsStudentsIndexRoute: typeof StudentsStudentsIndexRoute
}

const StudentsStudentsRouteChildren: StudentsStudentsRouteChildren = {
  StudentsStudentsIdRoute: StudentsStudentsIdRoute,
  StudentsStudentsIndexRoute: StudentsStudentsIndexRoute,
}

const StudentsStudentsRouteWithChildren =
  StudentsStudentsRoute._addFileChildren(StudentsStudentsRouteChildren)

interface StudentsRouteChildren {
  StudentsApplicationsRoute: typeof StudentsApplicationsRouteWithChildren
  StudentsStudentsRoute: typeof StudentsStudentsRouteWithChildren
  StudentsIndexRoute: typeof StudentsIndexRoute
}

const StudentsRouteChildren: StudentsRouteChildren = {
  StudentsApplicationsRoute: StudentsApplicationsRouteWithChildren,
  StudentsStudentsRoute: StudentsStudentsRouteWithChildren,
  StudentsIndexRoute: StudentsIndexRoute,
}

const StudentsRouteWithChildren = StudentsRoute._addFileChildren(
  StudentsRouteChildren,
)

interface UniversitiesRouteChildren {
  UniversitiesCoursesRoute: typeof UniversitiesCoursesRoute
  UniversitiesFeeStructureRoute: typeof UniversitiesFeeStructureRoute
  UniversitiesIntakesRoute: typeof UniversitiesIntakesRoute
  UniversitiesUniversitiesRoute: typeof UniversitiesUniversitiesRoute
  UniversitiesIndexRoute: typeof UniversitiesIndexRoute
  UniversitiesUniversitiesCodeRoute: typeof UniversitiesUniversitiesCodeRoute
}

const UniversitiesRouteChildren: UniversitiesRouteChildren = {
  UniversitiesCoursesRoute: UniversitiesCoursesRoute,
  UniversitiesFeeStructureRoute: UniversitiesFeeStructureRoute,
  UniversitiesIntakesRoute: UniversitiesIntakesRoute,
  UniversitiesUniversitiesRoute: UniversitiesUniversitiesRoute,
  UniversitiesIndexRoute: UniversitiesIndexRoute,
  UniversitiesUniversitiesCodeRoute: UniversitiesUniversitiesCodeRoute,
}

const UniversitiesRouteWithChildren = UniversitiesRoute._addFileChildren(
  UniversitiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdministrationRoute: AdministrationRoute,
  CommissionsRoute: CommissionsRoute,
  DashboardRoute: DashboardRoute,
  EnrollmentRoute: EnrollmentRoute,
  FeesRoute: FeesRoute,
  LoginRoute: LoginRoute,
  ReportsRoute: ReportsRoute,
  StudentsRoute: StudentsRouteWithChildren,
  SupportRoute: SupportRoute,
  UniversitiesRoute: UniversitiesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
